Coninna/config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :funds do
    member do
      get :confirm_email
    end
  end
  resources :categories
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => 'callbacks'}
  resources :users, path: :people
  resources :promises
  resources :projects
  get 'show_my', to: 'projects#show_my'
  get 'show_my_wishlist', to: 'user#show_my_wishlist'
  get 'users/:id' => 'users#show'
  root  'application#index'
  get 'statistics', to: 'users#statistics'
  get 'pending', to: 'projects#pending'
  get 'download', to: 'projects#download_file'

end

Coninna/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coninna Crowdfunding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--<header class="navbar navbar-default">
  <div class="container">
    <nav>
      <ul>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Projects', projects_path %>
        <% if user_signed_in?%>
          <%= link_to 'Wishlist', wishlist_path: @wishlist %>
          <%= link_to 'My profile', current_user %>
          <%= link_to 'My projects', project_path: @project %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to 'Login', new_user_session_path %>
          <%= link_to 'Sign Up', new_user_registration_path %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>-->
<header>
   <nav class="navbar navbar-expand-md  bg-dark navbar-dark fixed-top" >
  	<!-- Brand -->
  	<a class="navbar-brand" href="/">Coninna</a>

  	<!-- Toggler/collapsibe Button -->
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  	</button>

  	<!-- Navbar links -->
  	<div class="collapse navbar-collapse" id="collapsibleNavbar">
    	  <ul class="navbar-nav">

          <% if user_signed_in? && !current_user.admin%>
              <%= link_to '| Projects |', projects_path %>
              <%= link_to 'Wishlist |', wishlists_path %>
              <%= link_to 'My profile |', current_user %>
              <%= link_to 'My projects |', show_my_path %>
	  <%else%>
             	 <%= link_to '| Projects |', projects_path %>
              <% end %>
		
	  <% if user_signed_in? && current_user.admin %>
	        <%= link_to 'My profile |', current_user %>
                <%= link_to " Statistics |", statistics_path%>
                <%=link_to " Users information |",users_path %> 
		<%= link_to " Pending requests |", pending_path%>
 
          <% end %>
             
               
         
      	    
        </ul>
	       <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
            <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
           <%else%>
               <%= link_to '| Log In |   ', new_user_session_path %>
                 <%= link_to 'Sign Up |', new_user_registration_path %>
               <% end %>
         </ul>
  </div>
</nav> 
</header>
<div style="width:100; height:100; background-color:white">
	<h1> **</h1>
</div>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>