Coninna/config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :funds do
    member do
      get :confirm_email
    end
  end
  resources :categories
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => 'callbacks'}
  resources :users, path: :people
  resources :promises
  resources :projects
  get 'show_my', to: 'projects#show_my'
  get 'show_my_wishlist', to: 'user#show_my_wishlist'
  get 'users/:id' => 'users#show'
  root  'application#index'
  get 'statistics', to: 'users#statistics'
  get 'pending', to: 'projects#pending'
  get 'download', to: 'projects#download_file'

end

Coninna/app/models/project.rb
class Project < ApplicationRecord
	has_many :promises
	belongs_to :user
	has_many :category_projects
	has_many :categories, :through => :category_projects

	has_many :show_my_wishlist
	
	has_attached_file :photo, styles: { medium:"300x300>"}

	validates :title, :description, :days_to_go, :goal_amount, :actual_money, presence: true
	validates :goal_amount, numericality: { only_integer: true }
	validates :goal_amount, numericality: { greater_than: 0 }
	validates :actual_money, numericality: { only_integer: true }
	validates :actual_money, numericality: { greater_than: 0 }
	validates :days_to_go, numericality: { only_integer: true }
	validates :days_to_go, numericality: { greater_than: 0 }
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  def self.search(search)
    if search
      where("title LIKE ? or description LIKE ?", "%#{search}%", "%#{search}%") 
      
    else
      all
    end
    
  end
 

end

Coninna/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :download_file]

  # GET /projects
  # GET /projects.json
  def index
    @categories = Category.all

    @projects = Project.search(params[:searchbox])
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

	@project = Project.find(params[:id])
	@promises = Promise.all
	@actual = Fund.where(:project_id => @project.id).sum(:amount)
  end

  def show_my
    @projects = current_user.projects
    @actual = Fund.where(@projects).sum(:amount)
  end
  def pending
    @projects = Project.all
  end
  # GET /projects/new
  def new
    @project = Project.new
    
  end

  # GET /projects/1/edit
  def edit
  end
  def download_file
    @photo= Project.find(params[:id])

    send_file @photo.photo.path,
    :filename => @photo.photo_file_name,
    :type => @photo.photo_content_type,
    :disposition => "attachment"
    flash[:notice]= "Image downloaded"
  end


  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:description, :days_to_go, :goal_amount, :approves, :actual_money, :outstanding, :title, :descriptive_page, :photo, category_ids: [],  promises_attributes: [ :description, :amount, :delivery_date])
    end
end

Coninna/app/helpers/projects_helper.rb
module ProjectsHelper
end

Coninna/app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categories %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :days_to_go %>
    <%= f.number_field :days_to_go %>
  </div>

  <div class="field">
    <%= f.label :goal_amount %>
    <%= f.number_field :goal_amount %>
  </div>

  <div class="field">
    <%= f.label :actual_money %>
    <%= f.number_field :actual_money %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :descriptive_page %>
    <%= f.text_field :descriptive_page %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
 
  <% if user_signed_in? && current_user.admin %>
    <div class="field">
      <%= label_tag :outstanding %>
	    <%= f.check_box :outstanding %>
    </div>
    <div class="field">
      <%= label_tag :approved %>
	    <%= f.check_box :approves %>
    </div>
    <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Coninna/app/views/projects/edit.html.erb
<div  style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">Edit Project</h1>
</div>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Coninna/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div  style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">Projects</h1>
</div>
<% if user_signed_in? && !current_user.admin %>
  <%= link_to 'New Project', new_project_path , class: "btn btn-dark"%>
<% end %>
<% if user_signed_in? && current_user.admin%>

  <%= link_to 'New Category', new_category_path, class: "btn btn-dark" %>
<% end %>
<% if user_signed_in? && !current_user.admin %>
  <%= link_to 'Funded Projects', funds_path , class: "btn btn-dark"%>
<% end %>
<br>
<body><br>
<div class="row">
<div class="col-sm-3">
<%= form_tag({:controller => "projects", :action => "index"}, :method => :get) do %>

      <%= text_field_tag "searchbox", params[:searchbox] %>

      <%= submit_tag "Search", :name => nil %>

  <% end %></div>

  <% if user_signed_in? && current_user.admin %>
    <%= link_to 'Categories: ', categories_path %>
  <%else%>
    <h4>Categories: </h4>
    <%end%>
 <div class="col-sm-4">
   <% @categories.each do |cat|%>
     <%=link_to cat.name, cat %>
	<%end%>

</div>
</div>
</body>


<table>


  <tbody>
    <% @projects.each do |project| %>
      <% if project.approves? %>
	      <div class="row">
		<div class="col-sm-4" style="padding-left: 35px ;padding-top: 20px">
		  <%= image_tag project.photo.url(:medium), class: 'img-thumbnail' %>
		  <br>
		</div>
		<div class="col-sm-4" style="padding-top: 40px">
		  <h3><%= link_to project.title, project %></h3>
		  <p><%= project.description %></p>
		  <div class="col-sm-6">
		    <p>Goal: $<%=project.goal_amount %></p>
		  </div>
		  
		  <div class="col-sm-6">
		    <p>Days to go: <%= project.days_to_go%></p>
		  </div>
		
	<br>
		  <% if user_signed_in? && !current_user.admin %>
		  <div>
		    <!-- Trigger/Open The Modal -->
            <button id="myBtn" class= "btn btn-primary"data-toggle="modal" data-target="#myModal<%=project.id %>">Add To Wishlist</button>

            <!-- The Modal -->
            <div id="myModal<%=project.id %>" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <div class="modal-header">
                  <span class="close">&times;</span>
                  <h2>Add to Wishlist</h2>
                </div>
                <div class="modal-body">
		     
		     <a> You are adding <%=project.title%> to your wishlist! </a>
	
                  <%= form_for Wishlist.new do |f| %>
        
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.hidden_field :project_id, :value => project.id %>
		    
                </div>
                   <div class="modal-footer">
                     <%= f.submit "Add", class: "btn btn-primary"%>
                  <% end %>
                  </div>
                <div class="modal-footer">
                  <h3></h3>
                </div>
                </div>

            </div>

		  </div>
		  
		  <% end %>
		  <% if user_signed_in? && current_user.admin%>
	  		<%= link_to 'Edit', edit_project_path(project), class:"btn btn-default" %>
		        <%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-danger" %>
		 
		  <% end %>
		  <br>
		</div>
	      </div>
	    <% end %>
	    <% end %>
	  </tbody>
</table>

<br>

Coninna/app/views/projects/new.html.erb
<div style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">New Project</h1>
</div>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

Coninna/app/views/projects/pending.html.erb
<div  style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">Pending Projects</h1>
</div>

<table>

<% if Project.where(approves:false).count %>
  <h3 align="center" > Yay! No pending requests</h3>
<%end%>
  <tbody>
 
    <% @projects.each do |project| %>
      <% if !project.approves %>
	      <div class="row">
		<div class="col-sm-4" style="padding-left: 35px ;padding-top: 20px">
		  <%= image_tag project.photo.url(:medium), class: 'img-thumbnail' %>
		  <br>
		</div>
		<div class="col-sm-4" style="padding-top: 40px">
		  <h3><%= link_to project.title, project %></h3>
		  <p><%= project.description %></p>
		  <div class="col-sm-6">
		    <p>Goal: $<%=project.goal_amount %></p>
		  </div>
		  <div class="col-sm-6">
		    <p>Actual Money: $<%=project.actual_money %></p>
		  </div>
		  <div class="col-sm-6">
		    <p>Days to go: <%= project.days_to_go%></p>
		  </div>
		  <div class="progress">
	  		<div class="progress-bar" style="width:<%= (project.actual_money.to_f/project.goal_amount.to_f )*100%>% " role="progressbar" aria-valuenow="<%= ((project.actual_money.to_f/project.goal_amount.to_f )*100).to_int %>" aria-valuemin="0" aria-valuemax="<%=project.goal_amount%>"><%= ((project.actual_money.to_f/project.goal_amount.to_f )*100).to_int%>%</div>
		 </div>
	<br>

		  <% if @project.where(@project.approves => false).count == 0 %>
			<p> No pending requests <%=Project.where(project.approves => false).count %> </p>
		<%end%>
		  
		  <% if user_signed_in? && current_user.admin%>
	  		<%= link_to 'Edit', edit_project_path(project) %>
		        <%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %>
		  <% end %>
		  <br>
		</div>
	      </div>
	    <% end %>
	  
	    <% end %>
	  </tbody>
</table>

Coninna/app/views/projects/show.html.erb
<div  style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left"><%= @project.title %></h1>
</div>
<div class="container-fluid">
	<p>
	  <% if @project.photo.exists? %>
	    
	
	 <p> <%= link_to (image_tag( @project.photo.url(:medium), class:'img-thumbnail' )), download_path(id:@project), target:'_blank' %></p>

	
	<%end%>
	<p>
	  <strong>Category:</strong>
	  <% @project.categories.each do |category| %>
	    <%= category.name %>
	  <% end %>
	</p>
    <p>
      <strong>Promises:</strong>
      <% @project.promises.each do |promise| %>
        <div>
          <p> <strong>Description:</strong> <%= promise.description %>
              <strong> Amount: $ </strong><%= promise.amount %>
              <strong> Delivery date: </strong><%= promise.delivery_date %>
            <% if user_signed_in? && !current_user.admin %>
            <!-- Trigger/Open The Modal -->
            <button id="myBtn" data-toggle="modal" class= "btn btn-succes" data-target="#myModal<%=promise.id %>">Buy</button>

            <!-- The Modal -->
            <div id="myModal<%=promise.id %>" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <div class="modal-header">
                  <span class="close">&times;</span>
                  <h2>Promise</h2>
                </div>
                <div class="modal-body">
                  <%= form_for Fund.new do |f| %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>
		    <%= f.hidden_field :promise_id, :value => promise.id %>
	            <%= f.hidden_field :project_id, :value => @project.id %>
		    <%= f.hidden_field :amount, :value => nil %>

                    <p><strong>Description:</strong> <%= promise.description %>
                      <strong> Amount: $ </strong><%= promise.amount %>
                      <strong> Delivery date: </strong><%= promise.delivery_date %></p>
                    </div>
                    <div class="modal-footer">
                      <%= f.submit "Buy", class: "btn btn-primary"%>
                  <% end %>
        </div>
        <div class="modal-footer">
          <h3></h3>
        </div>
        </div>

        </div>
      <% end %>
      <%end%>
    </p>
	<p>
	  <strong>Owner:</strong>
	  <%= link_to @project.user.name , user_path(@project.user)%>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%#= raw Markdown.new(@project.description).to_html %>
    <%= markdown(@project.description) %>
	</p>

	<p>
	  <strong>Days to go:</strong>
	  <%= @project.days_to_go %>
	</p>

   <p>
    <strong>Goal amount: $</strong>
    <%= @project.goal_amount %></p>
    <p><strong>Actual Money: $</strong>
      <%= @actual %></p>

        <div class="col-sm-2">
	     <div class="progress">
	  		<div class="progress-bar" style="width:<%= (@actual.to_f/@project.goal_amount.to_f )*100%>%" role="progressbar" aria-valuenow="<%= ((@actual.to_f/@project.goal_amount.to_f )*100).to_int%>; color:black" aria-valuemin="0" aria-valuemax="<%=@project.goal_amount%>"><%= ((@actual.to_f/@project.goal_amount.to_f )*100).to_int%>%</div>
		 </div>
</div>


<br>

<p>
  <strong>Descriptive page:</strong>
  <%= @project.descriptive_page %>
</p>



<% if user_signed_in? %>
  <% if @project.user == current_user || current_user.admin%>
    <%= link_to 'Edit', edit_project_path(@project) , class:"btn btn-default"%>
    <%= link_to 'Destroy', @project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>


  <% else %>
    <div class="row">
    	<div class="col-sm-2">
	<% if user_signed_in? && !current_user.admin %>
            <!-- Trigger/Open The Modal -->
            <button id="myBtn" class= "btn btn-success"data-toggle="modal" data-target="#myModal<%=@project_id %>">Fund with money</button>

            <!-- The Modal -->
            <div id="myModal<%=@project_id %>" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <div class="modal-header">
                  <span class="close">&times;</span>
                  <h2>Fund</h2>
                </div>
                <div class="modal-body">
		              <input type="hidden" id="project_id" value="<%= @project.id %>">
	
                  <%= form_for Fund.new do |f| %>
        
                    <%= f.hidden_field :user_id, :value => current_user.id %>
                    <%= f.hidden_field :project_id, :value => @project.id %>
                    <%= f.hidden_field :promise_id, :value => nil %>
		    


		                   <div class="row">
                        <div class="col-sm-6">

                            <h3>Enter your amount: </h3>
                                  <%= f.number_field :amount%>
			   
                        </div>
                       </div>
                </div>
                   <div class="modal-footer">
                     <%= f.submit "Fund", class: "btn btn-primary"%>
                  <% end %>
                  </div>
                <div class="modal-footer">
                  <h3></h3>
                </div>
                </div>

            </div>

      <% end %>
      
    </p>
      	   
	
	<br>
    <div class="row">
    	<div class="col-sm-4">
     		 
  
		<!-- Trigger/Open The Modal -->
            <button id="Wish" class= "btn btn-primary"data-toggle="modal" data-target="#wish<%=@project.id%>">Add To Wishlist</button>

            <!-- The Modal -->
            <div id="wish<%=@project.id%>" class="modal">

              <!-- Modal content -->
              <div class="modal-content">
                <div class="modal-header">
                  <span class="close">&times;</span>
                  <h2>Add to Wishlist</h2>
                </div>
                <div class="modal-body">
		     <input type="hidden" id="project_id" value="<%= @project.id %>">
		     <p> You are adding <%=@project.title%> to your wishlist! </p>
	
                  <%= form_for Wishlist.new do |w| %>
        
                    <%= w.hidden_field :user_id, :value => current_user.id %>
                    <%= w.hidden_field :project_id, :value => @project.id %>
		    
                </div>
                   <div class="modal-footer">
                     <%= w.submit "Add", class: "btn btn-primary"%>
                  <% end %>
                  </div>
                <div class="modal-footer">
                  <h3></h3>
                </div>
                </div>

            </div>

      <% end %>
      






    </div>
    </div>
    
    <% end %>
<div>

    </div>


  

</div>

Coninna/app/views/projects/show_my.html.erb
<div style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">My Projects</h1>
</div>
<% if user_signed_in? %>
  <%= link_to 'New Project', new_project_path , class:"btn btn-dark" %>
<% end %>

<table>

  <tbody>


  <% current_user.projects.each do |project| %>
    <div class="row">
      <div class="col-sm-4" style="padding-left: 35px ;padding-top: 20px">
        <%= image_tag project.photo.url(:medium), class: 'img-thumbnail' %>
        <br>
      </div>
      <div class="col-sm-4" style="padding-top: 40px">
        <h3><%= link_to project.title, project %></h3>
        <p><%= project.description %></p>
        <div class="col-sm-6">
          <p>Goal: $<%= project.goal_amount %></p>
        </div>
        <div class="col-sm-6">
          <p>Acual Money: $<%= @actual %></p>
        </div>
        <div class="col-sm-6">
          <p>Days to go: <%= project.days_to_go %></p>
        </div>
	<div class="col-sm-6">
          <% if project.approves %>
          <p>Approved: Yes</p>
	<% else%>
		<p>Approved: No</p>
	<%end%>
        </div>
        <div class="col-sm-6">
          <% if user_signed_in? %>
            <div><%= link_to "New Promise", new_promise_path(:project => project.id) %> </div>
            <%= link_to 'Edit', edit_project_path(project) %>
            <%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </div>
        <br>
      </div>
    </div>
  <% end %>
  </tbody>
</table>

<br>