Coninna/config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :funds do
    member do
      get :confirm_email
    end
  end
  resources :categories
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => 'callbacks'}
  resources :users, path: :people
  resources :promises
  resources :projects
  get 'show_my', to: 'projects#show_my'
  get 'show_my_wishlist', to: 'user#show_my_wishlist'
  get 'users/:id' => 'users#show'
  root  'application#index'
  get 'statistics', to: 'users#statistics'
  get 'pending', to: 'projects#pending'
  get 'download', to: 'projects#download_file'

end

Coninna/app/models/fund.rb
class Fund < ApplicationRecord
  belongs_to :user
  belongs_to :promise
  private
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

Coninna/app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]


  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
    	
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
	 @funds = Fund.all
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        MoneyMailer.funding_confirmation(current_user, @fund).deliver_now
        Fund.find(@fund.id).update(:state => true)
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end


  end
  def confirm_fund
    user = Fund.find_by_confirm_token(params[:token])
    if user
      user.validate_email
      user.save(validate: false)
      redirect_to user
    else
      flash[:error] = "Sorry, user does not exist"
      redirect_to root_url
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:state, :user_id, :promise_id, :project_id, :amount)
    end
end

Coninna/app/helpers/funds_helper.rb
module FundsHelper
end

Coninna/app/views/funds/_form.html.erb
<%= form_for(fund) do |f| %>
  <% if fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :promise_id %>
    <%= f.text_field :promise_id %>
  </div>
   <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Coninna/app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

Coninna/app/views/funds/index.html.erb
<p id="notice"><%= notice %></p>
<div style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">Funded Projects</h1>
</div>

  <table>
    <thead>
      <tr>
        <th>State</th>
	<th colspan="4"></th>
        
        <th>Project</th>
	<th colspan="4"></th>
        <th>Amount</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @funds.each do |fund| %>
	<% if fund.user == current_user%>
		<% if fund.state %>
		<tr>
		  <td>Funded!</td>
		
		<th colspan="4"></th>
	      	
	      <td><%= link_to fund.project_id, project_path(fund.project_id) %></td>
		
	    
	 <th colspan="4"></th>
	    <% if fund.promise != nil %>
		   <td><%= fund.promise.amount %></td>
	    <%else%>
	      <td><%= fund.amount %></td>
		  <%end%>
		  
		
		</tr>
	      <% end %>
	      <%end%>
	<%end%>
    </tbody>
  </table>

  <br>

Coninna/app/views/funds/new.html.erb
<h1>New Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Back', funds_path %>

Coninna/app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>
<div style="width:100; height:100; background-color:lightpink; padding-top: 0px">
  <h1 style="font-size:50px; text-align:left">Funding</h1>
</div>

<p>
  <strong>State:</strong>
  <% if @fund.state %>
      <td>Funded!</td>
  <%else%>
	<td>Waiting</td>
  <%end%>
</p>

<p>
  <strong>User:</strong>
<% if @fund.user != nil %>
  <td><%= @fund.user.name %></td>
<%end%>


</p>

<p>
  <strong>Promise:</strong>
  <% if @fund.promise != nil %>
  <td><%= @fund.promise.description %></td>
  <% else %>
  <td> Funded with money </td>
<%end%>

</p>

<p>
  <strong>Project:</strong>
  <% if @fund.promise != nil %>
  <td><%= @fund.promise.project.title %></td>
  <% else %>
  <td><%= link_to @fund.project_id , project_path(@fund.project_id)%> </td>
<%end%>

</p>

<p>
  <strong>Amount:</strong>
   <% if @fund.promise != nil %>
    <%= @fund.promise.amount %>
<%else%>
  <%= @fund.amount %>
<%end%>
</p>

<%= link_to 'Edit', edit_fund_path(@fund) %> |
<%= link_to 'Back', funds_path %>